### ISSUE TITLE
Rename "hauptseite"-Djangoapp to "startpage" or "indexpage"

### ISSUE THREAD

**Issue by micha003** [wbgym-webteam/website#2]
Be careful to dont break anything :)

**Comment by JanaganSaravanan** [comment]
Hi! is this issue still open ? If yes, I would like to work on this.

**Comment by micha003** [comment]
@JanaganSaravanan it is still open!

**Comment by JanaganSaravanan** [comment]
Thank you for your response. I could not find any files other than LICENCE and Readme. can you guide me to the source code and files ?

**Comment by micha003** [comment]
The actual code is in the dev-Branch :)

**Comment by micha003** [comment]
Sorry @JanaganSaravanan , sooner or later there will be other issues :)
