### ISSUE TITLE
Division of the apps

### ISSUE THREAD

**Issue by micha003** [wbgym-webteam/website#3]
I'm not sure, if it's a good idea to seperate each topic in a different app. I think, they should be united, to get a better overview of all apps. This means, that we have to change the division of the django-apps, because I don't think, it is good, how we wanted to design it.

@DreamyK9 @Gundal-stack @MilimTheTrueOne 

I know Milim, that you are kinda triggered by the ping, but I don't care XD..... ITS IMPORTANT!

**Comment by DreamyK9** [comment]
If only anyone had pointed that out at our meeting... 🙃

**Comment by micha003** [comment]
WE DID IT!!! 👍🏻
