### ISSUE TITLE
Use of a miro whiteboard

### ISSUE THREAD

**Issue by micha003** [wbgym-webteam/website#8]
Hi Webteam, I wanted to ask you, what your thoughts of about a team whiteboard on [Miro)(miro.com) are. I think it will allow us to be much more productive in planning new features :)

I think Github Projects is also pretty good, but I miss the ability to draw and annotate...

AND you can connect Miro to Github :o (soon...)

**Comment by micha003** [comment]
I set a team there up, I will send a join link soon

**Comment by Gundal-stack** [comment]
We could also use Slack, which has GitHub and whiteboard implementations

**Comment by micha003** [comment]
That would be another good Alternative. Lets discuss it in the next session

**Comment by micha003** [comment]
WE DID IT!
